name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Test
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        python setup.py test